# Generated by Django 3.2.13 on 2022-05-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=70, null=True)),
                ('Age', models.CharField(max_length=70, null=True)),
                ('Gender', models.CharField(max_length=70, null=True)),
                ('DoctorEmail', models.CharField(max_length=70)),
                ('Status', models.CharField(max_length=70, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=70, null=True)),
                ('Age', models.CharField(max_length=70, null=True)),
                ('Gender', models.CharField(max_length=70, null=True)),
                ('DoctorEmail', models.CharField(max_length=70)),
                ('Status', models.CharField(max_length=70, null=True)),
            ],
        ),
    ]
