# Generated by Django 3.2.13 on 2022-05-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='DoctorEmail',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='DoctorEmail',
        ),
        migrations.AddField(
            model_name='doctor',
            name='Email',
            field=models.EmailField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='nurse',
            name='Email',
            field=models.EmailField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Age',
            field=models.IntegerField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='Age',
            field=models.IntegerField(max_length=70, null=True),
        ),
    ]
