# Generated by Django 3.2.13 on 2022-05-15 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_room_room_bed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='Age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='Age',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=70, null=True)),
                ('Status', models.CharField(max_length=70, null=True)),
                ('Condition', models.CharField(max_length=70, null=True)),
                ('Age', models.CharField(max_length=70, null=True)),
                ('Gender', models.CharField(max_length=70, null=True)),
                ('RegisterDate', models.CharField(max_length=70, null=True)),
                ('Branch', models.CharField(max_length=70, null=True)),
                ('Disease', models.CharField(max_length=70, null=True)),
                ('History', models.CharField(max_length=70, null=True)),
                ('OtherDiseases', models.CharField(max_length=70, null=True)),
                ('Diabeyic', models.CharField(max_length=70, null=True)),
                ('Smoker', models.CharField(max_length=70, null=True)),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProposalItems', to='hospital.doctor')),
                ('Nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProposalItems', to='hospital.nurse')),
                ('RoomID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ProposalItems', to='hospital.room_bed')),
            ],
        ),
    ]
