# Generated by Django 3.2.13 on 2022-05-15 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_auto_20220515_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='RoomID',
        ),
        migrations.AddField(
            model_name='patient',
            name='Bed',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='PatientBed', to='hospital.room_bed'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='Doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PatientDoctor', to='hospital.doctor'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Nurse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PatientNurse', to='hospital.nurse'),
        ),
        migrations.AlterField(
            model_name='room_bed',
            name='RoomID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RoomBeds', to='hospital.room'),
        ),
    ]
