# Generated by Django 3.2.13 on 2022-05-15 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_auto_20220515_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Bed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PatientBed', to='hospital.room_bed'),
        ),
    ]
