# Generated by Django 3.2.13 on 2022-05-15 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_alter_patient_bed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Bed',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Patient', to='hospital.room_bed'),
        ),
    ]
