# Generated by Django 3.2.13 on 2022-05-18 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_auto_20220515_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bed',
            name='Number',
        ),
        migrations.RemoveField(
            model_name='bed',
            name='Status',
        ),
    ]
