# Generated by Django 3.2.13 on 2022-05-24 12:55

from django.db import migrations, models
import hospital.models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_auto_20220520_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Img',
            field=models.ImageField(blank=True, upload_to=hospital.models.upload_to, verbose_name='ProposalItemImage'),
        ),
    ]
