# Generated by Django 3.2.13 on 2022-05-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0011_patient_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='RegisterDate',
            field=models.DateField(max_length=70, null=True),
        ),
    ]
