# Generated by Django 3.2.13 on 2022-05-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0013_alter_patient_otherdiseases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='History',
            field=models.DateField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='OtherDiseases',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
